name: Deploy to prod automatically on published release - GCP


on:
  release:
    # skal være [published] men skrur ikke på enda
    types: []

permissions: {}

jobs:
  deploy_to_prod:
    name: Deploy to prod
    #temp disable denne, kjører uansett on types in array er unspecified som er skummelt
    if: ${{ inputs.deploy_prod == true && github.ref == 'refs/heads/master' }}
    permissions:
      contents: read
      id-token: write
    uses: navikt/su-se-bakover/.github/workflows/reusable-deploy.yml@master
    with:
      var: image=europe-north1-docker.pkg.dev/nais-management-233d/supstonad/su-se-bakover-app:${{ github.sha }}
      cluster: prod-gcp
      resource: .nais/prod-gcp.yaml
