name: Deploy branch to GCP [manual deploy]
# If you want to deploy a branch (feature branch or even redeploy master/main) to dev-gcp (preprod) we use Github actions workflow_dispatch
# Goto https://github.com/navikt/su-se-bakover/actions/workflows/su-se-bakover-branch-deploy.yml choose a branch and deploy it
# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
on:
  workflow_dispatch:
    inputs:
      deploy_prod:
        description: 'Deploy to production'
        type: boolean
        required: false
        default: false

permissions: {}

jobs:
  verify-master-is-ancestor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - run: | # git merge-base returns 0 when master is ancestor, 1 if it is not (other positive numbers on error)
          set +e
          origin_master="$(git rev-parse origin/master)"
          head="$(git rev-parse HEAD)"
          echo "Hash for origin master: ${origin_master}. Hash for HEAD: ${head}."
          merge_base="$(git merge-base $origin_master HEAD)"
          echo "Merge-base: ${merge_base}"
          git merge-base --is-ancestor $origin_master HEAD
          return_code=$?
          echo "Return code of 'git merge-base': ${return_code}"
          if [[ return_code -gt 0 ]]; then
            echo "You have to merge origin/master before you can deploy a branch."
            exit 1
          fi
  build-test-push-image:
    name: Build, test and push image
    needs: verify-master-is-ancestor
    runs-on: ubuntu-latest-8-cores
    permissions:
      contents: read
      id-token: write # needed for push-image
    steps:
      - uses: actions/checkout@v5
      - name: Build and test
        uses: ./.github/actions/build-and-test
      - name: Push image
        uses: ./.github/actions/push-image
        with:
          tag: ${{ github.sha }}
          image_suffix: 'app'
  deploy-to-preprod:
    needs: build-test-push-image
    name: Deploy to preprod
    permissions:
      contents: read
      id-token: write
    uses: navikt/su-se-bakover/.github/workflows/reusable-deploy.yml@master
    with:
      cluster: dev-gcp
      var: image=europe-north1-docker.pkg.dev/nais-management-233d/supstonad/su-se-bakover-app:${{ github.sha }}
      resource: .nais/dev-gcp.yaml

  deploy-to-prod:
    needs: build-test-push-image
    if: ${{ inputs.deploy_prod == true && github.ref == 'refs/heads/master' }}
    name: Deploy to prod gcp
    permissions:
      contents: read
      id-token: write
    uses: navikt/su-se-bakover/.github/workflows/reusable-deploy.yml@master
    with:
      cluster: prod-gcp
      var: image=europe-north1-docker.pkg.dev/nais-management-233d/supstonad/su-se-bakover-app:${{ github.sha }}
      resource: .nais/prod-gcp.yaml
